/* 1.Feladat
SELECT  ROUND(AVG(CSILLAGOK_SZAMA) OVER(PARTITION BY TIPUS ORDER BY CSILLAGOK_SZAMA), 2) AS 'Átlag csillag típusonként',
        ROUND(AVG(CSILLAGOK_SZAMA) OVER(PARTITION BY HELY ORDER BY CSILLAGOK_SZAMA), 2) AS 'Átlag csilag helyenként'
FROM Szallashely
WHERE SZALLAS_NEV NOT LIKE '%-%'

2.feladat
SELECT  sz.SZOBA_ID,
        f.FOGLALAS_PK,
        DATEDIFF(DAY, f.METTOL,f.MEDDIG) AS 'Foglalási napok',
        LAG(DATEDIFF(DAY, f.METTOL,f.MEDDIG), 1, 0 )OVER (PARTITION BY sz.SZOBA_ID ORDER BY DATEDIFF(DAY, f.METTOL,f.MEDDIG))
FROM Foglalas f JOIN Szoba sz on f.SZOBA_FK = sz.SZOBA_ID*/
